bug:
  head: ["bug/*", "bugfix/*", "fix/*"]

build:
  head: "build/*"

doc:
  head: "doc/*"

example:
  head: "example/*"

performance:
  head: ["performance/*", "perf/*"]

qa:
  head: ["qa/*", "test/*"]

refactor:
  head: "refactor/*"

feature:
  head: ["feature/*", "feat/*"]

subtask:
  base: ["feature/*", "feat/*"]


