# Name should reflect when action occurs
name: Check if PR can Merge

on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify-merge:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Prevent POC/WIP branches
      run: |
        /bin/bash scripts/workflows/verify-merge.sh
        exit $?
      env:
        BRANCH: ${{ github.event.pull_request.head.ref }}


    # TODO:
    # - Prevent labeled:
    #    - `status: wip`
    #    - `status: blocked`?
    #    - https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#pull_request
    #       - get `number` from action.event and then get labels
    # - Prevent if merge branch has failing build action? 
    #    - https://github.com/cirruslabs/gh-submit-queue

    # - name: Label PR
    #  if: github.event.action == 'opened' # Only run the action when the PR was first opened
    #  uses: ffittschen/pr-branch-labeler@v1
    #  with:
    #    repo-token: ${{ secrets.GITHUB_TOKEN }}

